M48
; DRILL file {KiCad 7.0.10} date Wed 10 Jan 2024 19:28:40 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-10T19:28:40+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X3.2283Y-3.2677
X3.2283Y-5.6693
X4.4094Y-3.2677
X4.4094Y-5.6693
T2
X3.5295Y-5.0476
X3.7146Y-3.8677
M30
