M48
; DRILL file {KiCad 7.0.10} date Mon 15 Jan 2024 09:17:29 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-15T09:17:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1358
%
G90
G05
T1
X3.8469Y-3.2579
X4.0744Y-3.2579
T2
X3.2283Y-3.189
X3.2283Y-5.6693
X4.4094Y-3.189
X4.4094Y-5.6693
T3
X3.5295Y-5.0476
X3.7146Y-3.8677
M30
