#pragma once

#include <stdint.h>

typedef enum _moldError {
    MOLD_ERROR_INVALID_ERROR = 0,
    MOLD_ERROR_FAILED_TO_RESET_ERROR_COUNTS,
    MOLD_ERROR_INVALID_PARAMS_NULL_TERMINATE_AFTER_FIRST_WORD,
    MOLD_ERROR_INVALID_PARAMS_PARSE_ERROR_SUBCMD,
    MOLD_ERROR_INVALID_PARAMS_PARSE_CMD,
    MOLD_ERROR_INVALID_PARAMS_PARSE_FLASH_SUBCMD,
    MOLD_ERROR_INVALID_PARAMS_FLASH_IS_SECTOR_ERASED_NOT_AT_START_OF_SECTOR,
    MOLD_ERROR_INVALID_PARAMS_FLASH_IS_DATA_VALID_DATA_IS_NULL,
    MOLD_ERROR_INVALID_PARAMS_FLASH_SECTOR_ERASE_ERASE_FAILED,
    MOLD_ERROR_INVALID_PARAMS_FLASH_SECTOR_ERASE_NOT_AT_START_OF_SECTOR,
    MOLD_ERROR_FLASH_SECTOR_ERASE_ERASE_FAILED,
    MOLD_ERROR_INVALID_PARAMS_FLASH_READ_DATA_BUF_IS_NULL,
    MOLD_ERROR_INVALID_PARAMS_FLASH_READ_DATA_ADDRESS_OR_NBYTES_IS_TOO_HIGH,
    MOLD_ERROR_INVALID_PARAMS_FLASH_WRITE_DATA_DATA_IS_NULL,
    MOLD_ERROR_FLASH_WRITE_DATA_VALIDATION_FAILED,
    MOLD_ERROR_INVALID_PARAMS_FLASH_READ_BLOCK_BLOCK_IS_NULL,
    MOLD_ERROR_INVALID_PARAMS_FLASH_READ_BLOCK_ADDRESS_DOESNT_START_AT_BLOCK,
    MOLD_ERROR_INVALID_PARAMS_IS_BLOCK_FREE_ADDRESS_DOESNT_START_AT_BLOCK,

    MOLD_ERROR_TEST,

    // how many errors are there?
    MOLD_ERROR_NUM,
} MoldError;

void raise_error(MoldError error);

void reset_errors();

void list_errors();

uint8_t in_error_state();
